// Code generated by protoc-gen-go. DO NOT EDIT.
// source: foo.proto

package demo_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetFooReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Val                  int64    `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFooReq) Reset()         { *m = GetFooReq{} }
func (m *GetFooReq) String() string { return proto.CompactTextString(m) }
func (*GetFooReq) ProtoMessage()    {}
func (*GetFooReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_foo_214d71e34f04d866, []int{0}
}
func (m *GetFooReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFooReq.Unmarshal(m, b)
}
func (m *GetFooReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFooReq.Marshal(b, m, deterministic)
}
func (dst *GetFooReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFooReq.Merge(dst, src)
}
func (m *GetFooReq) XXX_Size() int {
	return xxx_messageInfo_GetFooReq.Size(m)
}
func (m *GetFooReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFooReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetFooReq proto.InternalMessageInfo

func (m *GetFooReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetFooReq) GetVal() int64 {
	if m != nil {
		return m.Val
	}
	return 0
}

type GetFooResp struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	Data                 string               `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	Shuzhu               []string             `protobuf:"bytes,4,rep,name=shuzhu" json:"shuzhu,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetFooResp) Reset()         { *m = GetFooResp{} }
func (m *GetFooResp) String() string { return proto.CompactTextString(m) }
func (*GetFooResp) ProtoMessage()    {}
func (*GetFooResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_foo_214d71e34f04d866, []int{1}
}
func (m *GetFooResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFooResp.Unmarshal(m, b)
}
func (m *GetFooResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFooResp.Marshal(b, m, deterministic)
}
func (dst *GetFooResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFooResp.Merge(dst, src)
}
func (m *GetFooResp) XXX_Size() int {
	return xxx_messageInfo_GetFooResp.Size(m)
}
func (m *GetFooResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFooResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetFooResp proto.InternalMessageInfo

func (m *GetFooResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetFooResp) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *GetFooResp) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *GetFooResp) GetShuzhu() []string {
	if m != nil {
		return m.Shuzhu
	}
	return nil
}

type GetBarReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBarReq) Reset()         { *m = GetBarReq{} }
func (m *GetBarReq) String() string { return proto.CompactTextString(m) }
func (*GetBarReq) ProtoMessage()    {}
func (*GetBarReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_foo_214d71e34f04d866, []int{2}
}
func (m *GetBarReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBarReq.Unmarshal(m, b)
}
func (m *GetBarReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBarReq.Marshal(b, m, deterministic)
}
func (dst *GetBarReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBarReq.Merge(dst, src)
}
func (m *GetBarReq) XXX_Size() int {
	return xxx_messageInfo_GetBarReq.Size(m)
}
func (m *GetBarReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBarReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetBarReq proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetFooReq)(nil), "demo.v1.GetFooReq")
	proto.RegisterType((*GetFooResp)(nil), "demo.v1.GetFooResp")
	proto.RegisterType((*GetBarReq)(nil), "demo.v1.GetBarReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Demo service

type DemoClient interface {
	// 接口定义
	GetFoo(ctx context.Context, in *GetFooReq, opts ...grpc.CallOption) (*GetFooResp, error)
	GetBar(ctx context.Context, in *GetBarReq, opts ...grpc.CallOption) (*GetFooResp, error)
}

type demoClient struct {
	cc *grpc.ClientConn
}

func NewDemoClient(cc *grpc.ClientConn) DemoClient {
	return &demoClient{cc}
}

func (c *demoClient) GetFoo(ctx context.Context, in *GetFooReq, opts ...grpc.CallOption) (*GetFooResp, error) {
	out := new(GetFooResp)
	err := grpc.Invoke(ctx, "/demo.v1.Demo/GetFoo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demoClient) GetBar(ctx context.Context, in *GetBarReq, opts ...grpc.CallOption) (*GetFooResp, error) {
	out := new(GetFooResp)
	err := grpc.Invoke(ctx, "/demo.v1.Demo/GetBar", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type demoNativeClient struct {
	cc DemoServer
}

func NewDemoNativeClient(cc DemoServer) DemoClient {
	return &demoNativeClient{cc}
}

func (c *demoNativeClient) GetFoo(ctx context.Context, in *GetFooReq, opts ...grpc.CallOption) (*GetFooResp, error) {
	out, err := c.cc.GetFoo(ctx, in)
	return out, err
}

func (c *demoNativeClient) GetBar(ctx context.Context, in *GetBarReq, opts ...grpc.CallOption) (*GetFooResp, error) {
	out, err := c.cc.GetBar(ctx, in)
	return out, err
}

// Server API for Demo service

type DemoServer interface {
	// 接口定义
	GetFoo(context.Context, *GetFooReq) (*GetFooResp, error)
	GetBar(context.Context, *GetBarReq) (*GetFooResp, error)
}

func RegisterDemoServer(s *grpc.Server, srv DemoServer) {
	s.RegisterService(&_Demo_serviceDesc, srv)
}

func _Demo_GetFoo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFooReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServer).GetFoo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/demo.v1.Demo/GetFoo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServer).GetFoo(ctx, req.(*GetFooReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Demo_GetBar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBarReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServer).GetBar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/demo.v1.Demo/GetBar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServer).GetBar(ctx, req.(*GetBarReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Demo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "demo.v1.Demo",
	HandlerType: (*DemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFoo",
			Handler:    _Demo_GetFoo_Handler,
		},
		{
			MethodName: "GetBar",
			Handler:    _Demo_GetBar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "foo.proto",
}

func init() { proto.RegisterFile("foo.proto", fileDescriptor_foo_214d71e34f04d866) }

var fileDescriptor_foo_214d71e34f04d866 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4a, 0xfb, 0x40,
	0x10, 0xc6, 0xd9, 0xa4, 0xf4, 0xcf, 0x4e, 0xf9, 0x4b, 0xd9, 0x42, 0x09, 0x41, 0xb0, 0xe4, 0x54,
	0x04, 0x37, 0xb4, 0x9e, 0xf4, 0x66, 0x91, 0x8a, 0xd7, 0xc5, 0x93, 0x17, 0x99, 0x9a, 0x4d, 0x1a,
	0x68, 0x32, 0x69, 0xb2, 0xc9, 0xc1, 0xa3, 0x3e, 0x82, 0x27, 0x9f, 0xcb, 0x57, 0xf0, 0x41, 0xc4,
	0x4d, 0x52, 0x14, 0xbd, 0xcd, 0xce, 0x7e, 0xdf, 0x37, 0xbf, 0xd9, 0x05, 0x1e, 0x13, 0xc9, 0xa2,
	0x24, 0x43, 0xe2, 0x5f, 0xa4, 0x33, 0x92, 0xcd, 0xc2, 0x3f, 0x49, 0x88, 0x92, 0x9d, 0x0e, 0x6d,
	0x7b, 0x53, 0xc7, 0xa1, 0x49, 0x33, 0x5d, 0x19, 0xcc, 0x8a, 0x56, 0xe9, 0x1f, 0x77, 0x02, 0x2c,
	0xd2, 0x10, 0xf3, 0x9c, 0x0c, 0x9a, 0x94, 0xf2, 0xaa, 0xbd, 0x0d, 0xce, 0x80, 0xdf, 0x68, 0xb3,
	0x26, 0x52, 0x7a, 0x2f, 0x8e, 0xc0, 0x49, 0x23, 0x8f, 0xcd, 0xd8, 0x9c, 0x2b, 0x27, 0x8d, 0xc4,
	0x18, 0xdc, 0x06, 0x77, 0x9e, 0x33, 0x63, 0x73, 0x57, 0x7d, 0x95, 0xc1, 0x0b, 0x03, 0xe8, 0xf5,
	0x55, 0xf1, 0xcd, 0xe0, 0x5a, 0xc3, 0x05, 0xc0, 0x63, 0xa9, 0xd1, 0xe8, 0xe8, 0x01, 0x8d, 0xf5,
	0x8d, 0x96, 0xbe, 0x6c, 0x01, 0x64, 0x4f, 0x28, 0xef, 0x7a, 0x42, 0xc5, 0x3b, 0xf5, 0x95, 0x11,
	0x02, 0x06, 0x11, 0x1a, 0xf4, 0x5c, 0x3b, 0xdd, 0xd6, 0x62, 0x0a, 0xc3, 0x6a, 0x5b, 0x3f, 0x6d,
	0x6b, 0x6f, 0x30, 0x73, 0xe7, 0x5c, 0x75, 0xa7, 0x60, 0x64, 0xa1, 0x57, 0x58, 0x2a, 0xbd, 0x5f,
	0xbe, 0x31, 0x18, 0x5c, 0xeb, 0x8c, 0xc4, 0x2d, 0x0c, 0x5b, 0x34, 0x21, 0x64, 0xf7, 0x3a, 0xf2,
	0xb0, 0x9b, 0x3f, 0xf9, 0xd5, 0xab, 0x8a, 0x60, 0xfa, 0xfc, 0xfe, 0xf1, 0xea, 0x8c, 0x83, 0x51,
	0xd8, 0x2c, 0xc2, 0x44, 0x1b, 0x19, 0x13, 0x5d, 0xb2, 0x53, 0xb1, 0xb6, 0x51, 0x2b, 0x2c, 0x7f,
	0x46, 0xb5, 0x13, 0xff, 0x8e, 0x9a, 0xd8, 0xa8, 0xff, 0xe2, 0x10, 0xb5, 0xc1, 0x72, 0xc5, 0xef,
	0xfb, 0x7f, 0xda, 0x0c, 0xed, 0xfa, 0xe7, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x48, 0x88,
	0x7e, 0xc4, 0x01, 0x00, 0x00,
}
